backend:
    name: github
    repo: wizcom-social/inorder-customers
    branch: main
    base_url: https://sveltia-cms-auth.social-96f.workers.dev

media_folder: assets/images
public_folder: /images
collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'content/blog'
      create: true
      slug: '{{slug}}'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: 'Summary', name: 'summary', widget: 'string', default: '""', required: false }
          - { label: 'Date', name: 'date', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Last Modified', name: 'lastmod', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Draft', name: 'draft', widget: 'boolean', required: false, default: false }
          - { label: 'Weight', name: 'weight', widget: 'number', required: false }
          - { label: 'Pinned', name: 'pinned', widget: 'boolean', required: false }
          - { label: 'Homepage', name: 'homepage', widget: 'boolean', required: false }
          - { label: 'SEO', name: 'seo', widget: 'object', required: false, collapsed: true, fields: [{ label: 'Title', name: 'title', widget: 'string', required: false }, { label: 'Description', name: 'description', widget: 'string', required: false }, { label: 'Canonical', name: 'canonical', widget: 'string', required: false }, { label: 'noindex', name: 'noindex', widget: 'boolean', default: false, required: false }] }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
    - name: 'guides'
      label: 'Guides'
      folder: 'content/docs/guides'
      create: true
      slug: '{{slug}}'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: 'Summary', name: 'summary', widget: 'string', default: '""', required: false }
          - { label: 'Date', name: 'date', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Last Modified', name: 'lastmod', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Draft', name: 'draft', widget: 'boolean', required: false, default: false }
          - { label: 'Weight', name: 'weight', widget: 'number', required: false }
          - { label: 'Table of Contents', name: 'toc', widget: 'boolean', required: false }
          - { label: 'SEO', name: 'seo', widget: 'object', required: false, collapsed: true, fields: [{ label: 'Title', name: 'title', widget: 'string', required: false }, { label: 'Description', name: 'description', widget: 'string', required: false }, { label: 'Canonical', name: 'canonical', widget: 'string', required: false }, { label: 'noindex', name: 'noindex', widget: 'boolean', default: false, required: false }] }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
    - name: 'POS'
      label: 'POS'
      folder: 'content/docs/pos'
      create: true
      slug: '{{slug}}'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: 'Summary', name: 'summary', widget: 'string', default: '""', required: false }
          - { label: 'Date', name: 'date', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Last Modified', name: 'lastmod', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Draft', name: 'draft', widget: 'boolean', required: false, default: false }
          - { label: 'Weight', name: 'weight', widget: 'number', required: false }
          - { label: 'Table of Contents', name: 'toc', widget: 'boolean', required: false }
          - { label: 'SEO', name: 'seo', widget: 'object', required: false, collapsed: true, fields: [{ label: 'Title', name: 'title', widget: 'string', required: false }, { label: 'Description', name: 'description', widget: 'string', required: false }, { label: 'Canonical', name: 'canonical', widget: 'string', required: false }, { label: 'noindex', name: 'noindex', widget: 'boolean', default: false, required: false }] }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
    - name: 'BackOffice'
      label: 'Back Office'
      folder: 'content/docs/backoffice'
      create: true
      slug: '{{slug}}'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: 'Summary', name: 'summary', widget: 'string', default: '""', required: false }
          - { label: 'Date', name: 'date', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Last Modified', name: 'lastmod', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Draft', name: 'draft', widget: 'boolean', required: false, default: false }
          - { label: 'Weight', name: 'weight', widget: 'number', required: false }
          - { label: 'Table of Contents', name: 'toc', widget: 'boolean', required: false }
          - { label: 'SEO', name: 'seo', widget: 'object', required: false, collapsed: true, fields: [{ label: 'Title', name: 'title', widget: 'string', required: false }, { label: 'Description', name: 'description', widget: 'string', required: false }, { label: 'Canonical', name: 'canonical', widget: 'string', required: false }, { label: 'noindex', name: 'noindex', widget: 'boolean', default: false, required: false }] }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
    - name: 'Mobile'
      label: 'inOrder Mobile'
      folder: 'content/docs/mobile'
      create: true
      slug: '{{slug}}'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: 'Summary', name: 'summary', widget: 'string', default: '""', required: false }
          - { label: 'Date', name: 'date', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Last Modified', name: 'lastmod', widget: 'datetime', required: false, format: 'YYYY-MM-DDTHH:mm:ssZ' }
          - { label: 'Draft', name: 'draft', widget: 'boolean', required: false, default: false }
          - { label: 'Weight', name: 'weight', widget: 'number', required: false }
          - { label: 'Table of Contents', name: 'toc', widget: 'boolean', required: false }
          - { label: 'SEO', name: 'seo', widget: 'object', required: false, collapsed: true, fields: [{ label: 'Title', name: 'title', widget: 'string', required: false }, { label: 'Description', name: 'description', widget: 'string', required: false }, { label: 'Canonical', name: 'canonical', widget: 'string', required: false }, { label: 'noindex', name: 'noindex', widget: 'boolean', default: false, required: false }] }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
